// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisableController from "./disable_controller"
application.register("disable", DisableController)

import SearchFormController from "./search_form_controller";
application.register("search-form", SearchFormController);

import AddImagesController from "./add_images_controller";
application.register("add-images", AddImagesController);

import HelloController from "./hello_controller"
application.register("hello", HelloController)
