// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddImagesController from "./add_images_controller"
application.register("add-images", AddImagesController)

import DisableController from "./disable_controller"
application.register("disable", DisableController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import GenerateImageController from "./generate_image_controller"
application.register("generate-image", GenerateImageController)

import GridController from "./grid_controller"
application.register("grid", GridController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageParserController from "./image_parser_controller"
application.register("image-parser", ImageParserController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NoticeController from "./notice_controller"
application.register("notice", NoticeController)

import OpensymbolsController from "./opensymbols_controller"
application.register("opensymbols", OpensymbolsController)

import Pwa__FormController from "./pwa/form_controller"
application.register("pwa--form", Pwa__FormController)

import Pwa__SyncController from "./pwa/sync_controller"
application.register("pwa--sync", Pwa__SyncController)

import PwaController from "./pwa_controller"
application.register("pwa", PwaController)

import ResizeController from "./resize_controller"
application.register("resize", ResizeController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import ShowController from "./show_controller"
application.register("show", ShowController)

import SpeakController from "./speak_controller"
application.register("speak", SpeakController)

import StaticImageController from "./static_image_controller"
application.register("static-image", StaticImageController)

import StripeController from "./stripe_controller"
application.register("stripe", StripeController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TurboNative__SignOutController from "./turbo_native/sign_out_controller"
application.register("turbo-native--sign-out", TurboNative__SignOutController)

import VoicesController from "./voices_controller"
application.register("voices", VoicesController)
