// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddImagesController from "./add_images_controller"
application.register("add-images", AddImagesController)

import DisableController from "./disable_controller"
application.register("disable", DisableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageParserController from "./image_parser_controller"
application.register("image-parser", ImageParserController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import ShowController from "./show_controller"
application.register("show", ShowController)

import SpeakController from "./speak_controller"
application.register("speak", SpeakController)

import StaticImageController from "./static_image_controller"
application.register("static-image", StaticImageController)

import WaitController from "./wait_controller"
application.register("wait", WaitController)
