services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: itty_bitty_boards
      POSTGRES_PASSWORD: itty_bitty_password
      POSTGRES_DB: itty_bitty_boards_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - BINDING=0.0.0.0
      - DEVISE_JWT_SECRET_KEY=secret
      - REDIS_URL=redis://redis:6379/1
      - REDIS_PROVIDER=REDIS_URL
      - DATABASE_USERNAME=itty_bitty_boards
      - DATABASE_PASSWORD=itty_bitty_password
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
  redis_data:
