# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.3.0
FROM registry.docker.com/library/ruby:$RUBY_VERSION-bookworm AS base

# Rails app lives here
WORKDIR /app

# Set environment
ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle"

# Install JavaScript dependencies
ARG NODE_VERSION=21.5.0
ARG YARN_VERSION=1.22.21
ENV PATH=/usr/local/node/bin:$PATH
RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    npm install -g yarn@$YARN_VERSION && \
    rm -rf /tmp/node-build-master

# Install packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl git libpq-dev libvips node-gyp pkg-config python-is-python3 postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Redis is run as a separate service in docker-compose.yml. Replace redis-server with a script to avoid Foreman error.
RUN echo 'echo "sleep infinity" > /usr/bin/redis-server' > /usr/bin/redis-server && chmod +x /usr/bin/redis-server

EXPOSE 4000
CMD ["sleep", "infinity"]
