require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/scenarios", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Scenario. As you add validations to Scenario, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Scenario.create! valid_attributes
      get scenarios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      scenario = Scenario.create! valid_attributes
      get scenario_url(scenario)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_scenario_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      scenario = Scenario.create! valid_attributes
      get edit_scenario_url(scenario)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Scenario" do
        expect {
          post scenarios_url, params: { scenario: valid_attributes }
        }.to change(Scenario, :count).by(1)
      end

      it "redirects to the created scenario" do
        post scenarios_url, params: { scenario: valid_attributes }
        expect(response).to redirect_to(scenario_url(Scenario.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Scenario" do
        expect {
          post scenarios_url, params: { scenario: invalid_attributes }
        }.to change(Scenario, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post scenarios_url, params: { scenario: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested scenario" do
        scenario = Scenario.create! valid_attributes
        patch scenario_url(scenario), params: { scenario: new_attributes }
        scenario.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the scenario" do
        scenario = Scenario.create! valid_attributes
        patch scenario_url(scenario), params: { scenario: new_attributes }
        scenario.reload
        expect(response).to redirect_to(scenario_url(scenario))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        scenario = Scenario.create! valid_attributes
        patch scenario_url(scenario), params: { scenario: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested scenario" do
      scenario = Scenario.create! valid_attributes
      expect {
        delete scenario_url(scenario)
      }.to change(Scenario, :count).by(-1)
    end

    it "redirects to the scenarios list" do
      scenario = Scenario.create! valid_attributes
      delete scenario_url(scenario)
      expect(response).to redirect_to(scenarios_url)
    end
  end
end
