# app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id               :bigint           not null, primary key
#  profileable_type :string
#  profileable_id   :bigint
#  username         :string
#  slug             :string
#  bio              :text
#  intro            :string
#  settings         :jsonb
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  placeholder      :boolean          default(FALSE)
#  claim_token      :string
#  claimed_at       :datetime
#  sku              :string
#  profile_kind     :string           default("safety"), not null
#  allow_discovery  :boolean          default(FALSE), not null
#
class Profile < ApplicationRecord
  belongs_to :profileable, polymorphic: true, optional: true

  has_many :page_follows, foreign_key: :followed_page_id, dependent: :destroy
  has_many :followers, through: :page_follows, source: :follower_user

  has_many :profile_views, dependent: :destroy

  has_one_attached :avatar
  has_one_attached :intro_audio
  has_one_attached :bio_audio

  has_one_attached :safety_id_png
  has_one_attached :safety_id_pdf
  has_one_attached :device_tag_png
  has_one_attached :device_tag_pdf

  # The care plan documents (Communicators::GenerateCarePlan). PDF only — a PNG
  # of a multi-page document is meaningless. Deliberately NOT generated by
  # #generate_attachments!; they're built on demand from the endpoint so a
  # profile save doesn't pay for two more Grover renders. See
  # .claude-notes/safety-profiles.md.
  has_one_attached :care_plan_pdf
  has_one_attached :care_emergency_plan_pdf

  # Slug rules — kept in sync with API::ProfilesController#check_slug and
  # Onboarding::Myspeak. The format is the public-URL part (e.g. /my/<slug>),
  # so we want lowercase, 3–40 chars, alphanumeric + hyphens, no leading or
  # trailing hyphen.
  SLUG_FORMAT = /\A[a-z0-9]([a-z0-9-]{1,38}[a-z0-9])?\z/.freeze
  SLUG_EDIT_WINDOW = 7.days

  # Routes that conflict with public-URL prefixes (`/my/:slug`, `/u/:slug`,
  # etc.) or that look administrative enough that we don't want anyone
  # squatting them as a public link.
  RESERVED_SLUGS = %w[
    admin api auth account help
    my u v p c m
    onboarding myspeak speakanyway
    signup signin login logout
    settings dashboard
    profile profiles claim
    public privacy terms support
  ].freeze

  # Instructional copy this app used to write into `bio` / `intro` on create.
  # It was never something a user typed, but it is stored exactly like text
  # that was — so `bio.present?` is not an "did the owner write this?" check,
  # and every MySpeak page that had not been personalized published
  # "Write a short bio about yourself…" to visitors as if the communicator had
  # said it. Nothing writes these strings any more; the constant exists so the
  # historical rows stay identifiable (see `seeded_text?` and the
  # `profiles:copy_onboarding_bio_to_emergency_notes` rake task).
  #
  # Compare whole strings, never a substring: a real bio that quotes the phrase
  # belongs to its author.
  SEEDED_TEXT = [
    "Write a short bio about yourself. This will help others understand who you are and what you do.",
    "Welcome to MySpeak! Personalize your page by adding a short introduction about yourself.",
    "Welcome to MySpeak! Personalize your page by adding a short introduction about yourself here.",
    "This is a placeholder profile waiting to be claimed. Once claimed, you can customize it and make it your own. You can add your own bio, avatar, and other details.",
    # Variants from lib/tasks/accounts.rake's placeholder task, which had its
    # own near-copy of Profile.create_placeholders.
    "This is a placeholder profile. Once claimed, you can customize it and make it your own. You can add your own bio, avatar, and other details.",
    "Welcome to MySpeak! Let's get started.",
  ].freeze

  def self.seeded_text?(value)
    SEEDED_TEXT.include?(value.to_s.strip)
  end

  validates :username, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true
  # Format/reserved/numeric checks run only on new records or when the slug
  # is actually being changed. This leaves legacy rows undisturbed when an
  # unrelated field (bio, intro, settings) is updated.
  validates :slug, format: { with: SLUG_FORMAT, message: "must be 3–40 lowercase letters, numbers, or hyphens" }, if: :slug_format_validatable?
  validate :slug_not_reserved, if: :slug_format_validatable?
  validate :slug_not_pure_numeric, if: :slug_format_validatable?
  validates :claim_token, presence: true, uniqueness: true, if: -> { placeholder? }

  before_validation :set_defaults, on: :create
  before_validation :ensure_slug, on: :create

  before_save :set_kind
  before_save :touch_slug_changed_at
  before_save :sanitize_theme_settings
  before_save :sanitize_care_settings

  has_rich_text :public_about
  has_rich_text :public_intro
  has_rich_text :public_bio

  # --- Kinds (no migration needed; stored in settings for now) ---
  # "safety"         => communicator safety profile
  # "public_page" => pro landing page (SLP/teacher/creator)
  # "placeholder" => unclaimed placeholder record
  PROFILE_KINDS = %w[safety public_page placeholder].freeze

  def safety?
    profile_kind == "safety"
  end

  # A communicator safety profile — checks both the stored kind and the
  # polymorphic owner, since some older rows may not have `profile_kind` set.
  # Drives random-slug generation and safety-card regeneration.
  def safety_profile?
    profile_kind == "safety" || profileable_type == "ChildAccount"
  end

  # --- Random slugs (safety profiles only) ---
  # Safety profiles get an unguessable slug instead of a name-derived one so a
  # child's public emergency page can't be found by guessing their name.
  # Excludes ambiguous characters (0/o, 1/l/i) so a slug read off a printed
  # card or device tag can't be mistyped. Example: "s-k8x2mf".
  RANDOM_SLUG_CHARS = (("a".."z").to_a + ("0".."9").to_a - %w[0 o 1 l i]).freeze
  RANDOM_SLUG_LENGTH = 6

  def self.generate_random_slug
    loop do
      candidate = "s-" + Array.new(RANDOM_SLUG_LENGTH) { RANDOM_SLUG_CHARS.sample(random: SecureRandom) }.join
      break candidate unless exists?(slug: candidate) || exists?(legacy_slug: candidate)
    end
  end

  def public_page?
    profile_kind == "public_page"
  end

  def placeholder_kind?
    profile_kind == "placeholder"
  end

  scope :available_placeholders, -> {
    where(placeholder: true, claimed_at: nil, sku: nil)
  }

  scope :unclaimed_placeholders, -> {
    where(placeholder: true, claimed_at: nil)
  }

  scope :public_pages, -> {
    where(profile_kind: "public_page", allow_discovery: true)
  }

  # --- Ownership helpers ---
  def owner_user_id
    return nil if profileable.nil?

    if profileable_type == "User"
      profileable&.id
    elsif profileable.respond_to?(:user_id)
      profileable&.user_id
    end
  end

  # The User who should receive safety-page view alerts (issue #384): the
  # communicator's owner (family/parent post-claim). Nil for non-communicator
  # profiles or unclaimed accounts.
  def alert_recipient
    return nil unless profileable_type == "ChildAccount"

    profileable&.owner
  end

  # Parents are notified by default when their child's safety page is viewed.
  # They can opt out per-profile by setting settings["view_alerts_enabled"]
  # to false (the existing settings: {} param on the profile-update endpoint
  # already accepts this). Stored as a string or boolean by the frontend.
  def view_alerts_enabled?
    raw = (settings || {})["view_alerts_enabled"]
    return true if raw.nil? # default ON (opt-out)

    ![false, "false", "0", 0].include?(raw)
  end

  def email
    return nil if profileable.nil?

    if profileable_type == "User"
      profileable&.email
    elsif profileable.respond_to?(:user_email)
      profileable&.user_email
    end
  end

  def name
    profileable.respond_to?(:name) ? profileable.name : username
  end

  # --- Public URLs ---
  def public_url
    return nil if slug.blank?

    base_url = ENV["FRONT_END_URL"] || "http://localhost:8100"
    role = profileable&.role.to_s

    if role.include?("vendor")
      "#{base_url}/v/#{slug}"
    elsif profileable_type == "User"
      "#{base_url}/u/#{slug}"
    else
      "#{base_url}/my/#{slug}"
    end
  end

  def claim_url
    return nil if claim_token.blank?
    "#{ENV["FRONT_END_URL"] || "http://localhost:8100"}/c/#{claim_token}"
  end

  def startup_url
    profileable&.startup_url
  end

  # --- Stable background color (was random before) ---
  RANDOM_COLORS = ["#FF5733", "#33FF57", "#3357FF", "#F1C40F", "#E74C3C", "#8E44AD", "#3498DB", "#2ECC71"].freeze

  def bg_color
    seed = (slug.presence || username.presence || id.to_s)
    idx = Zlib.crc32(seed) % RANDOM_COLORS.length
    RANDOM_COLORS[idx]
  end

  # --- Boards ---
  # Preloads matter here: both of these are serialized straight into the public
  # profile payload, and every board card reads display_image_url /
  # preview_image_url, which are ActiveStorage lookups.
  BOARD_CARD_PRELOADS = [{ preview_image_attachment: :blob }, { preset_display_image_attachment: :blob }].freeze

  def user_boards
    return [] if profileable.nil?
    return profileable.boards.main_boards.alphabetical.includes(:user, *BOARD_CARD_PRELOADS) if profileable_type == "User"
    []
  end

  # `favorite_boards` is polymorphic in RETURN TYPE, not just in receiver:
  # ChildAccount#favorite_boards returns ChildBoard join rows, User#favorite_boards
  # returns Boards. The preload has to follow that — `includes(board: ...)` on a
  # Board relation raises AssociationNotFoundError and 500s the public page.
  # Both branches still answer `public_card_view`, which is what the callers need.
  def communication_boards
    return [] unless profileable&.respond_to?(:favorite_boards)

    favorites = profileable.favorite_boards
    return [] if favorites.blank?

    if favorites.klass == Board
      favorites.includes(*BOARD_CARD_PRELOADS)
    else
      favorites.includes(board: BOARD_CARD_PRELOADS)
    end
  end

  def voice
    profileable&.respond_to?(:voice) ? profileable.voice : "polly:kevin"
  end

  def voice_speed
    profileable&.respond_to?(:voice_speed) ? profileable.voice_speed : 1
  end

  def public_boards
      communication_boards
  end

  # --- Attachments / CDN URLs ---
  def avatar_url
    return nil unless avatar.attached?
    key = avatar.blob.key
    return nil if key.blank?
    "#{ENV["CDN_HOST"]}/#{key}"
  end

  def intro_audio_url
    return nil unless intro_audio.attached?
    key = intro_audio.blob.key
    return nil if key.blank?
    "#{ENV["CDN_HOST"]}/#{key}"
  end

  def bio_audio_url
    return nil unless bio_audio.attached?
    key = bio_audio.blob.key
    return nil if key.blank?
    "#{ENV["CDN_HOST"]}/#{key}"
  end

  def set_kind
    if profileable_type == "User" && !public_page?
      self.profile_kind = "public_page"
    end
  end

  # --- Views (IMPORTANT: keep these separated) ---

  # Internal / authenticated view (safe to include settings, but still be careful)
  def api_view(viewer = nil)
    {
      id: id,
      username: username,
      slug: slug,
      slug_type: slug_type,
      slug_editable: slug_editable?,
      slug_changed_at: slug_changed_at,
      slug_editable_at: slug_editable_at,
      bio: bio,
      intro: intro,
      profile_kind: profile_kind,
      public_url: public_url,
      startup_url: startup_url,
      allow_discovery: allow_discovery,
      view_alerts_enabled: view_alerts_enabled?,
      name: name,

      # Keep full settings ONLY for authenticated/edit contexts
      settings: settings,

      user_boards: user_boards.map(&:api_view),

      avatar: avatar.attached? ? avatar_url : nil,
      intro_audio_url: intro_audio.attached? ? intro_audio_url : nil,
      bio_audio_url: bio_audio.attached? ? bio_audio_url : nil,

      profileable_type: profileable_type,
      profileable_id: profileable_id,
      owner_user_id: owner_user_id,

      can_edit: viewer&.can_edit_profile?(id, "User"),
      viewer: viewer&.id || "anonymous",

      claim_token: claim_token,
      claim_url: claim_url,
      public_about_html: safe_html(public_about&.body&.to_s),
      public_intro_html: safe_html(public_intro&.body&.to_s),
      public_bio_html: safe_html(public_bio&.body&.to_s)
    }
  end

  # Public-facing communicator/safety page view — do NOT leak email / full settings
  # Only communicator pages have a private login to offer. Users and vendors
  # sign in through the normal user flow, so this is always false for them.
  def communicator_sign_in_available?
    return false unless profileable_type == "ChildAccount"

    profileable.present? && profileable.sign_in_available?
  end

  def safety_view
    {
      id: id,
      username: username,
      name: profileable.respond_to?(:name) ? profileable.name : username,
      slug: slug,
      slug_editable_at: slug_editable_at,
      profile_kind: profile_kind,

      public_url: public_url,
      intro: intro,
      bio: bio,

      avatar: avatar_url,
      intro_audio_url: intro_audio_url,
      bio_audio_url: bio_audio_url,

      # Only page-safe settings. Medical info + emergency contacts + emergency
      # notes are deliberately withheld here and fetched separately via the
      # gated safety-details endpoint, which records the access + alerts the
      # parent. `has_safety_info` lets the frontend show the "Emergency Info"
      # button without leaking the underlying data.
      settings: public_settings(kind: :safety),
      has_safety_info: has_safety_info?,

      # Same contract for the care sections: the flag ships on page-open, the
      # data only via the gated care_view endpoint.
      has_care_info: has_care_info?,

      # Boards shown publicly should be safe/public
      public_boards: public_boards.map(&:public_card_view),
      general_public_boards: Board.public_board_cards,

      # If you need this for the UI, keep it minimal
      profileable_type: profileable_type,
      profileable_id: profileable_id,

      # Whether this communicator has a working private login, so the public
      # page can offer a "Sign in as {name}" CTA instead of dead-ending them.
      # A bare boolean — never the passcode.
      sign_in_available: communicator_sign_in_available?,

      claim_url: claim_url, # ok to show if you want the CTA
      public_about_html: safe_html(public_about&.body&.to_s),
      public_intro_html: safe_html(public_intro&.body&.to_s),
      public_bio_html: safe_html(public_bio&.body&.to_s),
      # NOTE: communicator_account intentionally omitted — the full
      # ChildAccount#api_view leaks parent email, supporter/supervisor
      # emails, passcode, and claim tokens. The frontend PublicProfile
      # component does not use this field.
    }
  end

  # Public Pro landing page view — also do NOT leak email / internal objects
  def public_page_view
    {
      id: id,
      username: username,
      name: profileable.respond_to?(:name) ? profileable.name : username,
      slug: slug,
      profile_kind: profile_kind,
      allow_discovery: allow_discovery,
      public_url: public_url,
      intro: intro,
      bio: bio,

      avatar: avatar_url,
      intro_audio_url: intro_audio_url,
      bio_audio_url: bio_audio_url,

      # Only allow landing-page-safe settings keys
      settings: public_settings(kind: :public_page),

      # If you want this on creator pages, keep it public-only
      public_boards: public_boards.map(&:public_card_view),
      user_boards: user_boards.map(&:public_page_card_view),
      general_public_boards: Board.public_board_cards,
      # NOTE: email intentionally omitted — use settings["show_email"]
      # on the frontend if the user opted in to displaying contact info.
      public_about_html: safe_html(public_about&.body&.to_s),
      public_intro_html: safe_html(public_intro&.body&.to_s),
      public_bio_html: safe_html(public_bio&.body&.to_s),
      # Use a minimal public-safe view instead of the full api_view which
      # leaks parent email, supporter/supervisor emails, and passcode.
      communicator_account: profileable_type == "ChildAccount" ? profileable.public_api_view : nil,
      sign_in_available: communicator_sign_in_available?
    }
  end

  def user_api_view
    {
      id: id,
      username: username,
      name: name,
      slug: slug,
      profile_kind: profile_kind,
      allow_discovery: allow_discovery,
      public_url: public_url,
      intro: intro,
      bio: bio,

      avatar: avatar_url,
      intro_audio_url: intro_audio_url,
      bio_audio_url: bio_audio_url,

      # Only allow landing-page-safe settings keys
      settings: public_settings(kind: :public_page),
      email: email,
    }
  end

  def placeholder_view
    {
      id: id,
      username: username,
      slug: slug,
      placeholder: placeholder?,
      profile_kind: profile_kind,
      public_url: public_url,
      claim_token: claim_token,
      claim_url: claim_url,
      sku: sku,
      general_public_boards: Board.public_board_cards,
    }
  end

  def safe_html(html)
    ActionController::Base.helpers.sanitize(
      html,
      tags: %w[p br strong em b i u ul ol li a blockquote h3 h4],
      attributes: %w[href target rel]
    )
  end


  # --- Public settings whitelist ---
  # Page-safe settings shown on the open MySpeak social page (GET public).
  # Nothing medical or contact-related lives here — the open page is the
  # everyday "social" surface. Sensitive fields are in SAFETY_SENSITIVE_KEYS.
  SAFETY_PAGE_KEYS = %w[
    pronouns
    device_notes
    theme
  ].freeze

  # Sensitive safety settings — medical details + emergency contacts +
  # emergency notes. These are NEVER sent on page-open; they're returned only
  # by the gated safety-details endpoint (POST public/:slug/safety_view), which
  # records the access and (throttled) alerts the parent (issue #384). Keeping
  # them off the open page puts the data behind the notification wall, not just
  # behind the UI modal.
  SAFETY_SENSITIVE_KEYS = %w[
    allergies
    medical_conditions
    medications
    other_conditions
    other_conditions_notes
    emergency_notes
    emergency_contacts
    ice_contact_1
    ice_contact_2
    ice_contact_3
    ice_contact_4
    ice_contact_5
  ].freeze

  # Kept for any external reference; the full set of keys the safety page can
  # surface across the open page + the gated reveal.
  SAFETY_PUBLIC_KEYS = (SAFETY_PAGE_KEYS + SAFETY_SENSITIVE_KEYS).freeze

  # --- MySpeak page theme (issue #476) ---
  # Owner-picked visual theme stored on settings["theme"]. Values render into
  # inline CSS on an unauthenticated public page, so the sanitizer below is the
  # server-side CSS-injection defense. Presets/palettes live frontend-only; the
  # backend only stores + validates. Whitelist, not blocklist — unknown keys
  # are dropped.
  THEME_HEX_KEYS = %w[accent bg_color border_color text_color].freeze
  THEME_SLUG_KEYS = %w[preset bg_style].freeze
  THEME_HEX_FORMAT = /\A#[0-9a-fA-F]{6}\z/.freeze
  THEME_SLUG_FORMAT = /\A[a-z0-9_-]{1,40}\z/.freeze

  # --- MySpeak care sections ---
  # Optional, structured "how to support this person day to day" sections stored
  # on settings["care"]. Deliberately NOT in SAFETY_PAGE_KEYS (they are not open
  # on page-load) and NOT in SAFETY_SENSITIVE_KEYS (they are not an emergency).
  # They are served only by the gated care-details endpoint
  # (POST public/:slug/care_view), which logs the access but does NOT fire the
  # parent's emergency-view alert — a bus driver checking a snack rule must not
  # read as someone opening the medical record.
  #
  # Shape:
  #   settings["care"] = {
  #     "order"    => ["communication", "c_7f3a91"],
  #     "sections" => {
  #       "communication" => { "enabled" => true, "values" => { ... } },
  #       "c_7f3a91"      => { "enabled" => true, "custom" => true,
  #                            "title" => "Sensory",
  #                            "items" => [{ "label" => ..., "value" => ... }] },
  #     },
  #   }
  #
  # Built-in sections validate every value against the registry below; custom
  # sections are free label/value pairs a parent adds themselves. Whitelist, not
  # blocklist — an unknown section, field, or option is dropped on save.
  #
  # NOTE: no care field may ever appear in a Suggestions::Registry context
  # allow-list. These are private care details, not copy to hand to OpenAI.
  # Two rules shape every field below, and a new one should follow them:
  #
  #   1. Presets are MULTI-SELECT. A single-select forces a parent to pick the
  #      one truest thing about a person whose support is layered — independent
  #      at home, hand-over-hand at school — and a half-true chip on a card a
  #      substitute reads is worse than no chip. It also collapses the
  #      "independent / some help / full help" scales, which said little on
  #      their own, into concrete supports someone can actually act on.
  #   2. Presets stay SHORT (3-4 options) and answer "which of these applies".
  #      Anything specific or provisional belongs in the section's detail lines
  #      ("Bus: back left seat, by the window"), which every section carries.
  #      That is what makes a short option list lossless rather than lossy.
  #
  # There is deliberately no per-section `notes` field: the detail lines are the
  # free-text surface, and two of them side by side just split the same answer.
  CARE_SECTIONS = {
    "communication" => {
      fields: [
        { key: "methods", type: :multi_select,
          options: %w[aac_device aac_book sign gestures some_speech eye_gaze
                      partner_assisted] },
        # Replaces a "how much help do you need" scale. What a helper needs is
        # the thing to DO, not a rating — and "wait and pause" carries the only
        # part of the old response_time field that changed anyone's behavior.
        { key: "what_helps", type: :multi_select,
          options: %w[keep_my_device_close model_on_my_device wait_and_pause
                      offer_choices] },
      ],
    },
    "personal_care" => {
      fields: [
        { key: "toileting", type: :multi_select,
          options: %w[independent needs_reminders needs_help toilet_training
                      pull_ups diapers] },
        { key: "schedule", type: :multi_select,
          options: %w[on_request scheduled_times] },
        { key: "hygiene", type: :multi_select,
          options: %w[handwashing toothbrushing face_and_hands hair_brushing] },
        { key: "dressing", type: :multi_select,
          options: %w[independent some_help full_help] },
      ],
    },
    "meals" => {
      fields: [
        { key: "eating", type: :multi_select,
          options: %w[food_cut_up needs_supervision fed_by_an_adult tube_fed] },
        { key: "textures", type: :multi_select,
          options: %w[regular soft chopped pureed thickened_liquids] },
        # Utensils and vessels. Straw preferences used to be two chips here;
        # they are a detail line now, where "no straw — he bites through them"
        # can say why, which is the part a substitute actually needs.
        { key: "equipment", type: :multi_select,
          options: %w[fork_and_spoon fingers adapted_utensils specific_cup] },
        { key: "preferences", type: :short_text },
      ],
    },
    # Sensory is its own section rather than a sub-topic of Meals, deliberately:
    # "won't eat anything cold" is a meals fact, but noise on the bus and lights
    # in a classroom cut across every other section and had nowhere to live.
    "sensory" => {
      fields: [
        { key: "sound", type: :multi_select,
          options: %w[loud_noises_hurt uses_ear_defenders warn_before_alarms
                      likes_music] },
        { key: "touch", type: :multi_select,
          options: %w[ask_before_touching dislikes_light_touch
                      likes_deep_pressure] },
        { key: "light", type: :multi_select,
          options: %w[bright_light_hurts flickering_bothers prefers_dim] },
        # The single most useful line on this section for someone with a
        # distressed person in front of them.
        { key: "calming", type: :short_text },
      ],
    },
    # Split from Getting around on purpose. A wheelchair or a pair of AFOs is
    # true all day, in every room — it is not a fact about the trip to school,
    # and burying it under transportation meant nobody filled it in.
    "mobility" => {
      fields: [
        { key: "equipment", type: :multi_select,
          options: %w[wheelchair walker_or_gait_trainer braces_or_afos
                      cane_or_crutches] },
        { key: "support", type: :multi_select,
          options: %w[independent standby_supervision hands_on_help
                      help_with_transfers] },
      ],
    },
    "transportation" => {
      fields: [
        # "walks", not "walker" — with a Mobility section next door, `walker`
        # reads as the device rather than "gets there on foot".
        { key: "school_travel", type: :multi_select,
          options: %w[bus car_rider walks wheelchair_van parent_pickup] },
        { key: "seating", type: :multi_select,
          options: %w[harness car_seat booster wheelchair_securement] },
        { key: "bus_info", type: :short_text },
      ],
    },
  }.freeze

  CARE_KEYS = %w[care].freeze

  # A parent-added section. The key is generated client-side; the format is what
  # keeps an arbitrary attacker-chosen key out of the settings hash.
  CARE_CUSTOM_KEY_FORMAT = /\Ac_[0-9a-f]{6}\z/.freeze

  MAX_CUSTOM_CARE_SECTIONS = 4
  MAX_CARE_CUSTOM_ITEMS = 8
  MAX_CARE_MULTI_SELECT = 10
  CARE_TITLE_MAX = 60
  CARE_ITEM_LABEL_MAX = 60
  CARE_ITEM_VALUE_MAX = 200
  CARE_SHORT_TEXT_MAX = 300

  # Options a parent may still HAVE but is no longer OFFERED.
  #
  # sanitize_care_settings is a before_save, so it re-cleans the whole care blob
  # every time a profile is saved for ANY reason — an avatar upload is enough.
  # That means deleting an option from CARE_SECTIONS doesn't just stop offering
  # it: it silently erases that answer from every profile still holding it, the
  # next time anything touches them. No error, no 422, and nothing left to
  # restore from.
  #
  # So retiring an option is two steps, not one:
  #
  #   1. Move the key here. The sanitizer keeps ACCEPTING it, so stored answers
  #      survive, and the editor stops OFFERING it (care_registry_view omits
  #      deprecated keys). Nobody new can pick it; nobody loses what they wrote.
  #   2. Once `rake care:remap_options` has moved the stored answers onto their
  #      replacements — and the reports say zero remain — delete the entry here.
  #
  # A rename is a remove plus an add: deprecate the old key, add the new one,
  # and map old => new below.
  #
  # Shape: { "section" => { "field" => { "old_option" => "new_option_or_nil" } } }
  # A nil replacement means "no equivalent — drop it on remap", which still only
  # happens when someone deliberately runs the task.
  #
  # Empty on purpose, and NOT because nothing has ever been cut. The reshape
  # that dropped echolalia, the help-level scales, and the per-section notes
  # fields landed BEFORE the feature was announced, when no profile held a
  # single care answer, so there was nothing to protect and the options were
  # deleted outright. That is a one-time licence which has now expired: every
  # later change has to go back through the two steps above.
  DEPRECATED_CARE_OPTIONS = {}.freeze

  def self.retired_care_options(section_key, field)
    DEPRECATED_CARE_OPTIONS.dig(section_key, field[:key])&.keys || []
  end

  # Every option the SANITIZER will accept: everything in the registry, plus
  # anything already lifted out of it but not yet migrated. A union rather than
  # a sum, so it holds whether the key is still listed in CARE_SECTIONS or not.
  def self.accepted_care_options(section_key, field)
    (field[:options] || []) | retired_care_options(section_key, field)
  end

  # What the editor should OFFER — the registry minus anything retired. Doing
  # the subtraction here is what makes retirement a ONE-line edit: add the key
  # to DEPRECATED_CARE_OPTIONS and it stops being offered while staying
  # acceptable. Deleting it from CARE_SECTIONS in the same breath is exactly the
  # move that destroys stored answers, so don't make that the required step.
  def self.offered_care_options(section_key, field)
    (field[:options] || []) - retired_care_options(section_key, field)
  end

  # The care schema as the editor needs it — the whole registry, its caps, and
  # the custom-key format, in one payload.
  #
  # This lives beside CARE_SECTIONS deliberately. The frontend used to carry a
  # hand-copied duplicate of every option key, and sanitize_care_settings drops
  # an unrecognized key rather than rejecting it — so a rename here silently
  # deleted the parent's answer on their next save, with no error and no 422.
  # Serving the registry means a change to the constant reaches the editor
  # without a frontend deploy, and there is no second copy to drift.
  #
  # Sections are an ARRAY, not a hash: CARE_SECTIONS is insertion-ordered and
  # that order is the order the editor renders in.
  #
  # Labels ride along too, resolved through CareLabels — the backend owns the
  # display strings as well as the schema now, so a server-rendered care sheet
  # and the on-screen card read identically and there is no second copy to
  # drift. See config/locales/care.en.yml.
  #
  # LABELS ARE ADDITIVE, AND MUST STAY THAT WAY. `options` is an array of plain
  # STRINGS and has to remain one: the deployed frontend parses it with
  # `asStringList(field?.options)` (src/data/careSections.ts), which yields []
  # for an array of objects — every section would silently lose its choices and
  # fall back to the bundled copy. So labels arrive as SIBLING keys (`label`,
  # `option_labels`) that an older client simply ignores.
  def self.care_registry_view(locale: I18n.locale)
    {
      locale: locale.to_s,
      sections: CARE_SECTIONS.map do |key, spec|
        {
          key: key,
          label: CareLabels.section(key, locale: locale),
          fields: spec[:fields].map do |field|
            out = {
              key: field[:key],
              type: field[:type],
              label: CareLabels.field(key, field[:key], locale: locale),
            }
            if field[:options]
              # Offered, not accepted: a retired option stays valid on save but is
              # never presented as a fresh choice.
              out[:options] = offered_care_options(key, field)
              # Labels, though, cover ACCEPTED — offered plus retired. A retired
              # option is still stored on real profiles and still has to render;
              # it just must never be offered. So this map is deliberately the
              # wider of the two.
              out[:option_labels] = CareLabels.options_map(key, field, locale: locale)
            end
            out
          end,
        }
      end,
      limits: {
        max_custom_sections: MAX_CUSTOM_CARE_SECTIONS,
        max_custom_items: MAX_CARE_CUSTOM_ITEMS,
        max_multi_select: MAX_CARE_MULTI_SELECT,
        title_max: CARE_TITLE_MAX,
        item_label_max: CARE_ITEM_LABEL_MAX,
        item_value_max: CARE_ITEM_VALUE_MAX,
        short_text_max: CARE_SHORT_TEXT_MAX,
      },
      custom_key_format: js_custom_key_format,
    }
  end

  # Ruby anchors \A and \z are not valid in a JavaScript RegExp, so translate
  # rather than shipping Regexp#source raw — a consumer that compiled it would
  # throw. Derived from the constant on purpose: a hand-written copy of the
  # pattern is exactly the kind of duplicate this endpoint exists to remove.
  def self.js_custom_key_format
    CARE_CUSTOM_KEY_FORMAT.source.sub('\A', "^").sub('\z', "$")
  end

  PUBLIC_PAGE_KEYS = %w[
    public_page
    socials
    shop_links
    public_links
    featured_board_ids
    role_badges
    show_email
    headline
  ].freeze

  def public_settings(kind:)
    raw = settings.is_a?(Hash) ? settings : {}

    keys =
      case kind
      when :safety then SAFETY_PAGE_KEYS
      when :public_page then PUBLIC_PAGE_KEYS
      else []
      end

    raw.slice(*keys)
  end

  def url_for_attachment(attachment)
    return if !attachment.attached?
    if ENV["ACTIVE_STORAGE_SERVICE"] == "amazon" || Rails.env.production?
      cdn_host = ENV["CDN_HOST"]
      if cdn_host
        "#{cdn_host}/#{attachment.key}" # Construct CloudFront URL
      else
        attachment.url # Fallback to the direct Active Storage URL
      end
    else
      attachment.url
    end
  end

  # True when the profile has any sensitive safety data (medical or emergency
  # contacts) worth revealing behind the wall. Drives the frontend's
  # "Emergency Info" button without exposing the data itself.
  def has_safety_info?
    raw = settings.is_a?(Hash) ? settings : {}
    SAFETY_SENSITIVE_KEYS.any? { |k| raw[k].present? }
  end

  # The sensitive safety settings withheld from the open page. Returned only by
  # the gated safety-details endpoint, after the access is recorded + the parent
  # alerted (issue #384).
  def safety_sensitive_settings
    raw = settings.is_a?(Hash) ? settings : {}
    raw.slice(*SAFETY_SENSITIVE_KEYS)
  end

  # Payload for the gated safety-details endpoint. Carries only the sensitive
  # fields the open page omits; the frontend merges these into the profile it
  # already loaded via #safety_view.
  def safety_details_view
    {
      id: id,
      settings: safety_sensitive_settings,
    }
  end

  # The sanitized care blob, always a Hash. Only ever reaches a visitor through
  # #care_details_view.
  def care_settings
    raw = settings.is_a?(Hash) ? settings : {}
    care = raw["care"]
    care.is_a?(Hash) ? care : {}
  end

  # True when at least one care section is filled in and enabled. Drives the
  # frontend's "Care & routines" button without exposing the data itself —
  # the same contract as has_safety_info?.
  def has_care_info?
    sections = care_settings["sections"]
    return false unless sections.is_a?(Hash)

    sections.any? { |_key, section| section.is_a?(Hash) && section["enabled"] != false }
  end

  # Payload for the gated care-details endpoint. Carries only the care blob the
  # open page omits; the frontend merges it into the profile it already loaded.
  def care_details_view
    {
      id: id,
      settings: { "care" => care_settings },
    }
  end

  def safety_contacts
    s = settings || {}
    keys = s.keys
            .select { |k| k.to_s.start_with?("ice_contact_") }
            .sort_by { |k| k.to_s.gsub("ice_contact_", "").to_i }

    keys.map { |k| s[k] }.compact.select do |contact|
      contact.present? &&
        (
          contact["name"].to_s.strip.present? ||
          contact["phone"].to_s.strip.present? ||
          contact["relationship"].to_s.strip.present?
        )
    end
  end

  def safety_display_name
    name.presence || username.presence || "Safety Info"
  end

  def device_tag_display_name
    name.presence || username.presence || "My Device"
  end

  # Freshness key for the generated communicator documents (safety ID card,
  # device tag, care plan). It must describe the CONTENT they render and
  # nothing else.
  #
  # Deliberately excludes `updated_at`: ActiveStorage's attachment
  # `belongs_to :record, touch: true`, so ATTACHING a generated document moves
  # it. The signature is stamped into the blob's metadata *before* the attach,
  # which meant it was stale the instant it was written — the next call
  # recomputed a different key, missed, and re-rendered through headless
  # Chrome. It only ever appeared to work because the value is truncated to
  # whole seconds (`to_i`), so a generate that finished inside the same
  # wall-clock second as the previous save happened to match. That is also why
  # it read as a flaky spec rather than a broken cache.
  #
  # Nothing meaningful is lost. These documents render the avatar (covered by
  # the blob id + checksum) and the care/emergency answers (covered by
  # `settings`). The communicator's name comes from `profileable`, whose
  # changes never touched this timestamp anyway.
  def safety_info_signature
    [
      avatar_attachment&.blob_id,
      avatar_attachment&.blob&.checksum,
      settings.to_json
    ].join("-")
  end

  def generate_attachments!
    Communicators::GenerateSafetyIdCard.call(self)
    Communicators::GenerateDeviceTag.call(self)
  end

  # --- Audio generation ---
  def open_ai_opts
    {}
  end

  def enqueue_audio_job_if_needed
    return if id.blank?

    # Use modern dirty tracking
    intro_changed = saved_change_to_intro? || (intro.present? && !intro_audio.attached?)
    bio_changed   = saved_change_to_bio? || (bio.present? && !bio_audio.attached?)

    return unless intro_changed || bio_changed

    Rails.logger.info "Enqueueing SaveProfileAudioJob for profile #{slug}"
    SaveProfileAudioJob.perform_async(id)
  end

  def update_audio(audio_type)
    voice = profileable&.respond_to?(:voice) ? (profileable.voice || "polly:kevin") : "polly:kevin"
    language = profileable&.respond_to?(:language) ? (profileable.language || "en") : "en"
    text = ""
    if audio_type == :intro
      text = intro
    elsif audio_type == :bio
      text = bio
    else
      Rails.logger.error "Invalid audio type #{audio_type} for profile #{slug}"
      return
    end

    # Gate on the field being synthesized, not on `intro`. This guard used to
    # be `return unless intro.present?` at the top of the method, so a profile
    # with a bio and no intro never got bio audio either — and the public page
    # falls back to synthesizing on every tap when a clip is missing, which is
    # a multi-second wait each time. A blank field is also not worth a Polly
    # call in its own right.
    return if text.blank?

    synth_io = VoiceService.synthesize_speech(text: text, voice_value: voice, language: language)
    return unless synth_io
    unless synth_io
      Rails.logger.error "**** ERROR - create_audio_from_text **** \nNo valid response from VoiceService.synthesize_speech.\n #{synth_io&.inspect}"
      return nil
    end

    unless synth_io.respond_to?(:rewind) && synth_io.respond_to?(:read)
      synth_io = StringIO.new(synth_io)
    end
    Rails.logger.info "Audio synthesized #{audio_type} successfully for profile #{slug}, now attaching..."

    if audio_type == :intro
      save_audio_intro(synth_io, voice, language)
    elsif audio_type == :bio
      save_audio_bio(synth_io, voice, language)
    end
  rescue => e
    Rails.logger.error "#{audio_type.to_s.capitalize} audio failed for profile #{slug}: #{e.message}"
    nil
  end

  def save_audio_intro(audio_io, voice_value, language = "en")
    filename = "#{label_for_filename}_intro.mp3"
    self.intro_audio.attach(io: audio_io, filename: filename, content_type: "audio/mpeg")
    self.reload # Ensure the attached intro_audio is available for URL generation
    self.intro_audio
  end

  def save_audio_bio(audio_io, voice_value, language = "en")
    filename = "#{label_for_filename}_bio.mp3"
    self.bio_audio.attach(io: audio_io, filename: filename, content_type: "audio/mpeg")
    self.reload # Ensure the attached bio_audio is available for URL generation
    self.bio_audio
  end

  def label_for_filename
    file_safe_slug = (slug.presence || username.presence || id.to_s).to_s.parameterize
    "#{file_safe_slug}_#{voice}"
  end

  # --- Placeholders / claiming ---
  def self.create_placeholders(number)
    urls = []
    number.times do
      placeholder_name = "MySpeak #{SecureRandom.hex(4)}"
      slug = placeholder_name.parameterize

      # No seeded bio/intro: `claim!` keeps whatever is stored, so placeholder
      # copy written here would follow the profile onto a real, claimed MySpeak
      # page. The claim screen's own copy explains an unclaimed page.
      profile = Profile.create!(
        username: placeholder_name,
        slug: slug,
        placeholder: true,
        claimed_at: nil,
        claim_token: SecureRandom.hex(10),
        settings: { "profile_kind" => "placeholder" },
      )
      profile.set_fake_avatar
      urls << profile.public_url
    end
    urls
  end

  def self.create_for_user(user, username = nil)
    username ||= user.username || SecureRandom.hex(4)
    slug = username.parameterize

    existing_profile = Profile.find_by(username: username) || Profile.find_by(slug: slug)
    return existing_profile if existing_profile&.profileable_type == "User" && existing_profile&.profileable_id == user.id
    return nil if existing_profile.present?

    profile = Profile.create!(
      username: username,
      profileable_type: "User",
      profileable_id: user.id,
      slug: slug,
      placeholder: false,
      claimed_at: Time.zone.now,
      claim_token: nil,
      settings: { "profile_kind" => "public_page" },
    )
    profile.set_fake_avatar
    profile
  end

  def claim!(username, existing_user)
    user_id = existing_user.id
    existing_communicator = ChildAccount.find_by(username: username, user_id: user_id)

    communicator =
      existing_communicator ||
      ChildAccount.create!(username: username, name: username, user_id: user_id)

    update!(
      profileable: communicator,
      placeholder: false,
      claimed_at: Time.zone.now,
      username: username,
      slug: username.parameterize,
    )

    set_fake_avatar unless avatar.attached?
    self
  end

  def self.generate_with_username(username, existing_user = nil)
    slug = username.parameterize

    existing_profile = Profile.find_by(username: username) || Profile.find_by(slug: slug)
    return nil if existing_profile.present?

    profile = Profile.create!(
      username: username,
      slug: slug,
      claimed_at: nil,
      claim_token: SecureRandom.hex(10),
      placeholder: true,
      settings: { "profile_kind" => "placeholder" },
    )

    if existing_user
      new_communicator_account = existing_user.communicator_accounts.create!(
        username: username,
        name: username,
      )
      profile.update!(profileable: new_communicator_account, claimed_at: Time.zone.now, placeholder: false)
    end

    profile.set_fake_avatar
    profile
  end

  # --- Defaults ---
  def set_defaults
    self.settings ||= {}

    # `bio` and `intro` are deliberately left nil when blank. They are PUBLIC —
    # the MySpeak page prints the bio as About Me and speaks the intro aloud —
    # so seeding them here published instructions to visitors in the owner's
    # voice. Blank is the honest state; the frontend supplies its own copy when
    # there is nothing to show. See SEEDED_TEXT.

    # If you want to infer kind automatically:
    self.settings["profile_kind"] ||= default_profile_kind
  end

  def ensure_slug
    return if slug.present?

    if safety_profile?
      self.slug = self.class.generate_random_slug
      self.slug_type = "random"
    elsif username.present?
      self.slug = username.to_s.parameterize
    end
  end

  # --- Slug edit window ---
  # Returns true if the slug can be changed right now — either it has never
  # been edited (post-create) or the SLUG_EDIT_WINDOW has elapsed since the
  # last edit. Admins bypass this at the controller layer.
  def slug_editable?
    # Random safety slugs are never user-editable — the whole point is that
    # they stay unguessable and stable for printed cards / device tags.
    return false if slug_type == "random"
    return true if slug_changed_at.blank?
    slug_changed_at < SLUG_EDIT_WINDOW.ago
  end

  def slug_editable_at
    return nil if slug_changed_at.blank?
    slug_changed_at + SLUG_EDIT_WINDOW
  end

  # Cross-system uniqueness check. The onboarding flow already blocks slugs
  # that collide with any Profile.slug, Profile.username, or
  # ChildAccount.username — we mirror that here so editing and onboarding
  # agree on what "available" means.
  def self.slug_available?(value, except_id: nil)
    value = value.to_s.strip.downcase
    return false if value.blank?

    profile_scope = Profile.where(slug: value)
                           .or(Profile.where(username: value))
                           .or(Profile.where(legacy_slug: value))
    profile_scope = profile_scope.where.not(id: except_id) if except_id
    return false if profile_scope.exists?

    !ChildAccount.exists?(username: value)
  end

  # Reason codes mirror the JSON returned by ProfilesController#check_slug so
  # both the controller and the UI can use the same vocabulary.
  def self.slug_unavailable_reason(value)
    value = value.to_s.strip.downcase
    return :format if value.blank? || !value.match?(SLUG_FORMAT)
    return :reserved if RESERVED_SLUGS.include?(value)
    return :reserved if value.match?(/\A\d+\z/)
    return :taken unless slug_available?(value)
    nil
  end

  private

  def slug_format_validatable?
    slug.present? && (new_record? || slug_changed?)
  end

  def slug_not_reserved
    return if slug.blank?
    errors.add(:slug, "is reserved") if RESERVED_SLUGS.include?(slug)
  end

  def slug_not_pure_numeric
    return if slug.blank?
    errors.add(:slug, "cannot be all numbers") if slug.match?(/\A\d+\z/)
  end

  # Records the moment slug changes — but only for edits, not the initial
  # create. Onboarding-generated slugs should not consume the 7-day window.
  def touch_slug_changed_at
    return unless slug_changed?
    return if new_record?
    self.slug_changed_at = Time.current
  end

  # Whitelist + format-validate settings["theme"] on every save. Theme values
  # render into inline CSS on an unauthenticated public page, so this is the
  # CSS-injection defense. Hex fields must be #RRGGBB; preset/bg_style must be
  # simple slugs; everything else is dropped. A non-hash or empty theme clears
  # the key entirely (issue #476).
  def sanitize_theme_settings
    return unless settings.is_a?(Hash)
    return unless settings.key?("theme")

    raw = settings["theme"]
    unless raw.is_a?(Hash)
      settings.delete("theme")
      return
    end

    clean = {}
    THEME_HEX_KEYS.each do |k|
      v = raw[k].to_s.strip
      clean[k] = v if v.match?(THEME_HEX_FORMAT)
    end
    THEME_SLUG_KEYS.each do |k|
      v = raw[k].to_s.strip
      clean[k] = v if v.match?(THEME_SLUG_FORMAT)
    end

    if clean.empty?
      settings.delete("theme")
    else
      settings["theme"] = clean
    end
  end

  # Whitelist + validate settings["care"] on every save. The controller permits
  # `settings: {}` wholesale, so this is the only thing standing between a
  # request body and an unauthenticated public page — same role
  # sanitize_theme_settings plays for the theme. Unknown sections, unknown
  # fields, and out-of-registry option values are dropped rather than rejected:
  # a stale frontend must not be able to 422 a parent out of saving.
  def sanitize_care_settings
    return unless settings.is_a?(Hash)
    return unless settings.key?("care")

    raw = settings["care"]
    unless raw.is_a?(Hash)
      settings.delete("care")
      return
    end

    raw_sections = raw["sections"]
    raw_sections = {} unless raw_sections.is_a?(Hash)

    requested_order = raw["order"].is_a?(Array) ? raw["order"].map(&:to_s) : []
    present_keys = raw_sections.keys.map(&:to_s)
    # The parent's ordering decides which custom sections survive the cap, so
    # walk the ordered keys first and only then whatever else is in the hash.
    candidate_keys = (requested_order & present_keys) | present_keys

    clean_sections = {}
    custom_count = 0

    candidate_keys.each do |key|
      section = raw_sections[key]
      next unless section.is_a?(Hash)

      cleaned =
        if CARE_SECTIONS.key?(key)
          clean_builtin_care_section(key, section)
        elsif key.match?(CARE_CUSTOM_KEY_FORMAT) && custom_count < MAX_CUSTOM_CARE_SECTIONS
          clean_custom_care_section(section)
        end
      next if cleaned.nil?

      custom_count += 1 unless CARE_SECTIONS.key?(key)
      clean_sections[key] = cleaned
    end

    if clean_sections.empty?
      settings.delete("care")
      return
    end

    order = requested_order.uniq.select { |k| clean_sections.key?(k) }
    order += (clean_sections.keys - order)

    settings["care"] = { "order" => order, "sections" => clean_sections }
  end

  def clean_builtin_care_section(key, section)
    raw_values = section["values"]
    raw_values = {} unless raw_values.is_a?(Hash)

    clean_values = {}
    CARE_SECTIONS.fetch(key)[:fields].each do |field|
      raw_value = raw_values[field[:key]]

      # Validated against ACCEPTED options — what's offered now plus anything
      # retired but not yet migrated — so retiring an option can't delete a
      # parent's stored answer behind their back. See DEPRECATED_CARE_OPTIONS.
      accepted = self.class.accepted_care_options(key, field)

      cleaned =
        case field[:type]
        when :multi_select
          next unless raw_value.is_a?(Array)
          raw_value.map(&:to_s).uniq
                   .select { |v| accepted.include?(v) }
                   .first(MAX_CARE_MULTI_SELECT)
        when :single_select
          value = raw_value.to_s
          value if accepted.include?(value)
        when :short_text
          care_text(raw_value, CARE_SHORT_TEXT_MAX)
        end

      clean_values[field[:key]] = cleaned if cleaned.present?
    end

    # Detail lines. The preset chips answer "which of these applies"; the real
    # thing a parent needs to hand a substitute is usually specific and
    # provisional — "Bus: back left seat, by the window". That doesn't compress
    # into a chip, so a built-in section carries the same label/value rows a
    # custom one does. These are the ONLY free-text surface on a built-in
    # section, which is why the option lists above can stay short.
    items = clean_care_items(section["items"])

    return nil if clean_values.empty? && items.empty?

    cleaned = { "enabled" => care_enabled?(section["enabled"]), "values" => clean_values }
    cleaned["items"] = items if items.any?
    cleaned
  end

  # Shared by built-in and custom sections — same caps, same stripping, same
  # "a row with neither a label nor a value isn't a row" rule.
  def clean_care_items(raw_items)
    return [] unless raw_items.is_a?(Array)

    raw_items.filter_map do |item|
      next unless item.is_a?(Hash)

      label = care_text(item["label"], CARE_ITEM_LABEL_MAX)
      value = care_text(item["value"], CARE_ITEM_VALUE_MAX)
      next if label.blank? && value.blank?

      { "label" => label.to_s, "value" => value.to_s }
    end.first(MAX_CARE_CUSTOM_ITEMS)
  end

  def clean_custom_care_section(section)
    title = care_text(section["title"], CARE_TITLE_MAX)
    return nil if title.blank?

    items = clean_care_items(section["items"])

    return nil if items.empty?

    {
      "enabled" => care_enabled?(section["enabled"]),
      "custom" => true,
      "title" => title,
      "items" => items,
    }
  end

  # Care values render as text on an unauthenticated page, so markup is stripped
  # rather than escaped — there is no field here where a tag is meaningful.
  def care_text(value, limit)
    text = ActionController::Base.helpers.strip_tags(value.to_s).squish
    return nil if text.blank?

    text[0, limit]
  end

  # Enabled unless the owner explicitly turned the section off. A section that
  # arrives without the flag is one a parent just filled in.
  def care_enabled?(value)
    ![false, "false", "0", 0].include?(value)
  end

  public

  def default_profile_kind
    # sensible default without breaking existing behavior
    return "placeholder" if placeholder?
    return "public_page" if profileable_type == "User"
    "safety"
  end

  # --- Avatar generation ---
  def set_fake_avatar
    url =
      "https://ui-avatars.com/api/?name=#{URI.encode_www_form_component(username)}&background=random&size=128"
    avatar.attach(io: URI.open(url), filename: "#{slug}.png")
  end

  private

  def attach_audio_bytes(attachment, bytes, filename)
    tempfile = Tempfile.new([filename, ".mp3"])
    tempfile.binmode
    tempfile.write(bytes)
    tempfile.rewind

    attachment.attach(
      io: tempfile,
      filename: filename,
      content_type: "audio/mpeg",
    )
  ensure
    tempfile.close! if tempfile
  end
end
