module Boards
  # Rebuilds the medium/small (and xs/xxs) tile layouts from the authored LARGE
  # layout, so a board reads well on tablets and phones without ever losing a
  # tile. The lg layout is the source of truth and is never modified.
  #
  # Why this exists: sm/md layouts were generated by a count-based packer that
  # sliced tiles by COUNT, not width — so a row of multi-width tiles overflowed
  # the column count and the frontend had to rescue it at render time
  # (repackLayout). This reflows from the lg reading order into a width-aware,
  # occupancy-tracked pack at each screen's (proportional) column count, so the
  # persisted sm/md layout is clean and matches what every view renders.
  #
  # Distinct from Boards::LayoutRepacker: that one only nudges OVERFLOW tiles
  # back inside their existing grid (a data-repair safety net); this one does a
  # full reflow of md/sm from lg (the intentional responsive layout).
  module ScreenReflow
    module_function

    # Screens we derive from lg. xs/xxs are mirrors of sm (same as the rest of
    # the app, e.g. BoardImage#initial_layout).
    DERIVED_SCREENS = %w[md sm].freeze
    SM_MIRRORS = %w[xs xxs].freeze

    # Reflow the given screens from lg and persist. `screens` defaults to md+sm
    # but a caller can narrow it (e.g. to skip a screen the user hand-arranged).
    # Returns the list of screens rewritten (empty when there's nothing to do).
    # Pass dry_run: true to compute without saving.
    def reflow!(board, screens: DERIVED_SCREENS, dry_run: false)
      screens = Array(screens) & DERIVED_SCREENS
      return [] if screens.empty?

      ordered = lg_reading_order(board)
      return [] if ordered.empty?

      return screens if dry_run

      screens.each do |screen|
        columns = board.get_number_of_columns(screen).to_i
        columns = 1 if columns < 1
        packed = pack(ordered, columns)

        apply_screen!(packed, screen)
        SM_MIRRORS.each { |mirror| apply_screen!(packed, mirror) } if screen == "sm"
      end

      # Rebuild the denormalized board.layout (lg/md/sm) from the now-updated
      # per-tile layouts, reusing the single writer so the shape stays in lockstep.
      board.board_images.reset
      Boards::LayoutRepacker.resync_board_layout!(board)
      screens
    end

    # board_images in lg reading order: top-to-bottom, left-to-right by the lg
    # cell, falling back to the authored `position` when a tile has no lg cell.
    def lg_reading_order(board)
      board.board_images.order(:position).to_a.sort_by.with_index do |bi, i|
        cell = bi.layout.is_a?(Hash) ? bi.layout["lg"] : nil
        if cell
          [0, cell["y"].to_i, cell["x"].to_i, i]
        else
          [1, 0, 0, i] # no lg cell: keep authored order, after positioned tiles
        end
      end
    end

    # Row-major pack with occupancy tracking. Places each tile at the first free
    # top-left cell that fits its w×h without overlap. Width is clamped to the
    # column count and height to 2 (the grid assumes short tiles), mirroring
    # Board#pack_layout_row_major. Returns [{ board_image:, cell: }] pairs.
    def pack(ordered_board_images, columns)
      occupied = Set.new
      ordered_board_images.map do |bi|
        src = source_cell(bi)
        w = src[:w].clamp(1, columns)
        h = src[:h].clamp(1, 2)

        x, y = first_free_cell(occupied, columns, w, h)
        h.times { |dy| w.times { |dx| occupied << [x + dx, y + dy] } }

        { board_image: bi, cell: { "i" => bi.id.to_s, "x" => x, "y" => y, "w" => w, "h" => h } }
      end
    end

    # Preferred w/h come from the lg cell so a tile authored wide/tall on lg
    # stays as wide/tall as the smaller grid allows.
    def source_cell(board_image)
      cell = board_image.layout.is_a?(Hash) ? board_image.layout["lg"] : nil
      {
        w: [cell&.dig("w").to_i, 1].max,
        h: [cell&.dig("h").to_i, 1].max,
      }
    end
    private_class_method :source_cell

    def first_free_cell(occupied, columns, w, h)
      y = 0
      loop do
        (0..(columns - w)).each do |x|
          fits = (0...h).all? { |dy| (0...w).all? { |dx| !occupied.include?([x + dx, y + dy]) } }
          return [x, y] if fits
        end
        y += 1
      end
    end
    private_class_method :first_free_cell

    # Write the packed cells onto each board_image's layout[screen] — the
    # primary source of truth the native viewer reads. board.layout is rebuilt
    # from these afterward by LayoutRepacker.resync_board_layout!.
    def apply_screen!(packed, screen)
      packed.each do |entry|
        bi = entry[:board_image]
        bi.layout ||= {}
        bi.layout[screen] = entry[:cell]
        bi.save!
      end
    end
    private_class_method :apply_screen!
  end
end
